import {describe,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {defaultPreferences} from '../settings/preferences';
import {resolveEnvironment,customMeditation,warmFoundation,silentRecipe,validRecipe,environmentPlan,activeRecipe,type SoundRecipe} from '../meditation/environment';
import {freezeSound} from '../meditation/profile';
import {createSnapshot,type PracticeConfig} from '../session/config';
import {DeterministicSessionEngine} from '../session/engine';
import {PracticeRuntime} from '../session/runtime';
import {WakeLockController} from '../session/wake-lock';
import {FakeTiming} from './fake-time';
import {NoiseController} from '../audio/noise';
import {BinauralController} from '../audio/binaural';
import {BackgroundController} from '../media/background';
import {MeditationSignals} from '../audio/meditation-signals';
import {BuddyDatabase} from '../storage/database';
import {RoutineRepository} from '../routines/repository';
import {Routines} from '../features/routines/Routines';
import {repairDraft,validateRoutine} from '../routines/model';
import type {Routine,RoutineStage} from '../types/domain';

const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
const med=(id='med',policy:'defaults'|'silent'|'custom'='custom',sound=customMeditation(defaultPreferences()),seconds=600):RoutineStage=>({id,kind:'meditation',presetId:'meditation',durationSeconds:seconds,audioPolicy:policy,...(policy==='custom'?{sound}:{})});
const pattern:RoutineStage={id:'breath',kind:'custom-pattern',presetId:'custom-pattern',inhaleSeconds:4,holdInSeconds:0,exhaleSeconds:6,holdOutSeconds:0,cycles:1};
const settle:RoutineStage={id:'settle',kind:'settling',presetId:'settling',durationSeconds:30};
const routine=(stages:RoutineStage[]=[pattern,settle,med()],foundation:SoundRecipe|null=warmFoundation(defaultPreferences())):Routine=>({id:'routine',name:'Acoustic test',createdAt:'2026-10-09',updatedAt:'2026-10-09',stages,...(foundation?{foundation}:{})});
function snapshot(r:Routine,p=defaultPreferences()){const config:PracticeConfig={kind:'routine',routine:r};return createSnapshot(config,undefined,undefined,{...freezeSound(p),environment:resolveEnvironment(config,p)});}
function native(){
    const sources:any[]=[],oscillators:any[]=[],gains:any[]=[];
    const node=()=>({connect:vi.fn(),disconnect:vi.fn()});
    const source=()=>({...node(),start:vi.fn(),stop:vi.fn(),onended:undefined as undefined|(()=>void)});
    const context={state:'running',currentTime:0,createBufferSource:()=>{const s={...source(),buffer:null,loop:false};sources.push(s);return s;},createOscillator:()=>{const s={...source(),frequency:{value:0}};oscillators.push(s);return s;},createChannelMerger:()=>node(),createGain:()=>{const n={...node(),gain:{value:1,setValueAtTime:vi.fn(),linearRampToValueAtTime:vi.fn(),exponentialRampToValueAtTime:vi.fn(),cancelScheduledValues:vi.fn(),cancelAndHoldAtTime:vi.fn(),setTargetAtTime:vi.fn()}};gains.push(n);return n;}};
    return {context,sources,oscillators,gains,port:()=>({context,input:{}} as any)};
}
function fakeMedia(){const audio:any={src:'',currentSrc:'',paused:true,ended:false,currentTime:0,duration:600,volume:1,loop:false,addEventListener:vi.fn(),removeAttribute:vi.fn(()=>audio.src=''),load:vi.fn(),pause:vi.fn(()=>audio.paused=true),play:vi.fn(async()=>{audio.paused=false;})};return audio;}

describe('versioned acoustic recipes and immutable inheritance',()=>{
    it('rejects a frozen environment missing a meditation recipe instead of reading live defaults',()=>{const r=routine(),config:PracticeConfig={kind:'routine',routine:r},p=defaultPreferences(),sound={...freezeSound(p),environment:resolveEnvironment(config,p)};sound.environment.blocks={};expect(()=>createSnapshot(config,undefined,undefined,sound)).toThrow('repair');});
    it.each([['texture','red'],['source','https://outside.invalid'],['noiseLevel',.36],['musicLevel',NaN],['toneLevel',.31],['opening','future'],['closing',false],['signalLevel',-1],['version',2],['loop',0],['mode','future']] as const)('rejects invalid %s without clamping',(key,value)=>{expect(validRecipe({...customMeditation(defaultPreferences()),[key]:value})).toBe(false);});
    it('resolves defaults, two custom blocks and Silent independently at Start',()=>{const p=defaultPreferences(),a=customMeditation(p),b={...a,texture:'off' as const,source:'ambience.floating',mode:'baseline' as const,opening:'bowl' as const,closing:'off' as const};p.meditation.binaural.mode='layered';const s=snapshot(routine([med('defaults','defaults'),med('a','custom',a),med('b','custom',b),med('quiet','silent')]),p);p.meditation.binaural.mode='off';a.toneLevel=.3;expect(s.meditationSound!.environment!.blocks.defaults.mode).toBe('layered');expect(s.meditationSound!.environment!.blocks.a.toneLevel).toBe(.08);expect(s.meditationSound!.environment!.blocks.b).toEqual(b);expect(s.meditationSound!.environment!.blocks.quiet).toMatchObject({source:'none',texture:'off',mode:'off',opening:'off',closing:'off'});expect(Object.isFrozen(s.stages.find(s=>s.blockId==='a')!.soundRecipe)).toBe(true);});
    it('legacy whole-practice Floating continues into inherited meditation without rewriting its row',()=>{const p=defaultPreferences();p.background={source:'ambience.floating',mode:'entire',loop:true};const r=routine([pattern,med('m','defaults')],null),before=structuredClone(r),s=snapshot(r,p),time=new FakeTiming(),engine=new DeterministicSessionEngine(time,time);engine.start(s);expect(environmentPlan(engine.getState())?.source).toBe('ambience.floating');time.jump(26000);engine.reconcile();expect(environmentPlan(engine.getState())?.source).toBe('ambience.floating');expect(r).toEqual(before);expect(r.foundation).toBeUndefined();});
    it('legacy silent block suppresses every frozen layer and signals',()=>{const p=defaultPreferences();p.background={source:'ambience.floating',mode:'entire',loop:true};expect(snapshot(routine([med('m','silent')],null),p).stages[3].soundRecipe).toEqual(silentRecipe(p));});
    it('Warm is active in first Prepare and same parent key across breathing/settling/meditation',()=>{const time=new FakeTiming(),engine=new DeterministicSessionEngine(time,time);engine.start(snapshot(routine()));const key=environmentPlan(engine.getState())!.key;for(const ms of [0,4000,6000,3000,10000,3000,30000,3000]){time.jump(ms);engine.reconcile();expect(environmentPlan(engine.getState())).toMatchObject({key,texture:'brown'});}});
    it.each([0,1,59999,60000])('Release %sms leaves the foundation and shifts the actual meditation window',offset=>{const round:RoutineStage={id:'round',kind:'hormesis-round',presetId:'hormesis-round',cycles:20,intervalSeconds:2,retentionSeconds:60};const time=new FakeTiming(),engine=new DeterministicSessionEngine(time,time);engine.start(snapshot(routine([round,settle,med()])));time.jump(95000+offset);engine.reconcile();engine.releaseRetention();engine.releaseRetention();const remaining=61000;time.jump(remaining);engine.reconcile();expect(engine.getState().stage?.phase).toBe('block-transition');expect(environmentPlan(engine.getState())?.texture).toBe('brown');expect(activeRecipe(engine.getState())?.closing).toBe('bowl');});
    it('Start Again retains all resolved settings while a new Start uses new defaults',()=>{const time=new FakeTiming(),p=defaultPreferences(),audio:any={enter(){},cancelStage(){},cancelSession(){},unlock:async()=>{},setPreferences(){},resynchronize(){},diagnostics:()=>({scheduled:0,skipped:0,failures:[],playing:0,state:'running'}),subscribe:()=>()=>{}};const runtime=new PracticeRuntime(time,time,audio,new WakeLockController(undefined,()=>true),async()=>{});const config:PracticeConfig={kind:'routine',routine:routine([med('m','defaults')])};runtime.preferencesChanged(p);runtime.start(config);const frozen=runtime.engine.getState().snapshot!.meditationSound!;runtime.engine.stop();p.meditation.noise='off';p.background.source='ambience.homeAgain';runtime.preferencesChanged(p);runtime.start(config,frozen);expect(runtime.engine.getState().snapshot!.meditationSound).toEqual(frozen);runtime.engine.stop();runtime.start(config);expect(runtime.engine.getState().snapshot!.meditationSound!.environment!.blocks.m.texture).toBe('off');runtime.engine.stop();});
});

describe('one acoustic lifetime and transition cleanup',()=>{
    it('a normal three-second handoff starts a 25-second change, while explicit silence ends at the boundary',()=>{const p=defaultPreferences(),time=new FakeTiming(),engine=new DeterministicSessionEngine(time,time),media={...warmFoundation(p),texture:'off' as const,source:'ambience.floating'};engine.start(snapshot(routine([pattern,med()],media)));time.jump(23000);engine.reconcile();expect(engine.getState().stage?.phase).toBe('block-transition');expect(environmentPlan(engine.getState())?.ramp).toBe(25);engine.stop();engine.start(snapshot(routine([pattern,med('quiet','silent')],media)));time.jump(23000);engine.reconcile();expect(environmentPlan(engine.getState())?.ramp).toBe(3);engine.stop();});
    it('generated to selected audio keeps its bed until that selected source is ready',async()=>{const f=native(),time=new FakeTiming(),noise=new NoiseController(f.port,async()=>({length:1024,numberOfChannels:2} as AudioBuffer)),engine=new DeterministicSessionEngine(time,time),media={...warmFoundation(defaultPreferences()),texture:'off' as const,source:'ambience.floating'};let ready=false;noise.setMediaReady(()=>ready);engine.subscribe(()=>noise.sync(engine.getState()));engine.start(snapshot(routine([pattern,med('m','custom',media)])));await flush();time.jump(23000);engine.reconcile();expect(f.sources[0].stop).not.toHaveBeenCalled();ready=true;noise.sync(engine.getState());expect(f.sources[0].stop).toHaveBeenCalledWith(25);engine.stop();noise.dispose();});
    function controllers(r=routine()) {const f=native(),time=new FakeTiming(),noise=new NoiseController(f.port,async()=>({length:1024,numberOfChannels:2} as AudioBuffer)),tones=new BinauralController(f.port,time),engine=new DeterministicSessionEngine(time,time);engine.subscribe(()=>{noise.sync(engine.getState());tones.sync(engine.getState());});engine.start(snapshot(r));return{...f,time,noise,tones,engine};}
    it('one Warm source spans all blocks; rapid cues do not pump its gain',async()=>{const f=controllers();await flush();for(const ms of [4000,6000,3000,10000,3000,30000,3000]){f.time.jump(ms);f.engine.reconcile();await flush();f.noise.setDucking(true);f.noise.setDucking(false);}expect(f.sources).toHaveLength(1);expect(f.noise.diagnostics().duckFactor).toBe(1);expect(f.gains[0].gain.linearRampToValueAtTime).toHaveBeenCalledTimes(1);f.noise.dispose();f.tones.dispose();});
    it('six Layered oscillators enter only at the meditation lead-in, without replacing Warm',async()=>{const r=customMeditation(defaultPreferences());r.mode='layered';const f=controllers(routine([pattern,settle,med('m','custom',r)]));await flush();expect(f.oscillators).toHaveLength(0);f.time.jump(56000);f.engine.reconcile();expect(f.oscillators).toHaveLength(6);await flush();expect(f.sources).toHaveLength(1);f.engine.stop();for(const s of [...f.sources,...f.oscillators])s.onended?.();expect(f.noise.diagnostics().activeNodes).toBe(0);expect(f.tones.diagnostics().activeOscillators).toBe(0);});
    it('short custom block keeps its mode saved but creates no oscillators',()=>{const r={...customMeditation(defaultPreferences()),mode:'layered' as const};const f=controllers(routine([med('m','custom',r,60)]));expect(f.oscillators).toHaveLength(0);expect(activeRecipe(f.engine.getState())?.mode).toBe('layered');f.noise.dispose();});
    it('silent pre-boundary fade is bounded by the actual window; Stop cancels the retiring source',async()=>{const f=controllers(routine([settle,med('silent','silent')]));await flush();f.time.jump(22000);f.engine.reconcile();expect(f.sources[0].stop).toHaveBeenCalledWith(24);f.engine.stop();expect(f.sources[0].stop).toHaveBeenLastCalledWith(.05);f.sources[0].onended();expect(f.noise.diagnostics().activeNodes).toBe(0);});
    it('hide/suspension cancels nodes and late synthesis cannot rejoin an obsolete parent',async()=>{let resolve!:(b:AudioBuffer)=>void;const f=native(),time=new FakeTiming(),noise=new NoiseController(f.port,()=>new Promise(r=>resolve=r)),engine=new DeterministicSessionEngine(time,time);engine.subscribe(()=>noise.sync(engine.getState()));engine.start(snapshot(routine()));noise.visibilityChanged(false);engine.stop();resolve({length:1024,numberOfChannels:2} as AudioBuffer);await flush();expect(f.sources).toHaveLength(0);expect(noise.diagnostics().activeNodes).toBe(0);});
    it('compatible Floating retains playing position through every stage and frozen preference changes',async()=>{const a=fakeMedia(),time=new FakeTiming(),player=new BackgroundController({resolve:async()=>({url:'floating',owned:false,name:'Floating'})},()=>a),engine=new DeterministicSessionEngine(time,time),recipe={...warmFoundation(defaultPreferences()),texture:'off' as const,source:'ambience.floating'};engine.subscribe(()=>player.sync(engine.getState()));engine.start(snapshot(routine([pattern,settle,med('m','custom',recipe)],recipe)));await flush();a.currentTime=42;const plays=a.play.mock.calls.length;for(const ms of [13000,10000,3000,30000,3000]){time.jump(ms);engine.reconcile();await flush();expect(a.currentTime).toBe(42);}const p=defaultPreferences();p.background.source='ambience.homeAgain';player.setPreferences(p);expect(player.getState().source).toBe('ambience.floating');expect(a.play).toHaveBeenCalledTimes(plays);player.dispose();});
    it('Floating to Warm waits for the generated bed then fades 25 seconds instead of cutting',async()=>{vi.useFakeTimers();try{const a=fakeMedia(),time=new FakeTiming(),player=new BackgroundController({resolve:async()=>({url:'floating',owned:false,name:'Floating'})},()=>a),engine=new DeterministicSessionEngine(time,time),recipe={...warmFoundation(defaultPreferences()),texture:'off' as const,source:'ambience.floating'};let ready=false;player.setNoiseReady(()=>ready);engine.subscribe(()=>player.sync(engine.getState()));engine.start(snapshot(routine([pattern,med()],recipe)));await flush();vi.advanceTimersByTime(700);a.currentTime=20;time.jump(26000);engine.reconcile();expect(a.paused).toBe(false);ready=true;player.sync(engine.getState());expect(player.diagnostics().transportFade?.duration).toBe(25000);expect(a.paused).toBe(false);vi.advanceTimersByTime(25000);expect(a.paused).toBe(true);expect(a.currentTime).toBe(20);player.dispose();}finally{vi.useRealTimers();}});
    it('late missing-media readiness after Stop cannot start or replace playback',async()=>{let resolve!:(v:any)=>void;const a=fakeMedia(),time=new FakeTiming(),player=new BackgroundController({resolve:()=>new Promise(r=>resolve=r)},()=>a),engine=new DeterministicSessionEngine(time,time),recipe={...warmFoundation(defaultPreferences()),source:'ambience.floating'};engine.subscribe(()=>player.sync(engine.getState()));engine.start(snapshot(routine([pattern],recipe)));engine.stop();resolve({url:'late',owned:false,name:'Late'});await flush();expect(a.play).not.toHaveBeenCalled();player.dispose();});
    it('missing selected audio reports a visible error without changing engine or recipe',async()=>{const a=fakeMedia(),time=new FakeTiming(),player=new BackgroundController({resolve:async()=>{throw new Error('That local audio is no longer available.');}},()=>a),engine=new DeterministicSessionEngine(time,time),recipe={...warmFoundation(defaultPreferences()),source:'local:missing'};engine.subscribe(()=>player.sync(engine.getState()));engine.start(snapshot(routine([pattern],recipe)));await flush();expect(player.getState().error).toContain('no longer available');expect(engine.getState().status).toBe('running');expect(engine.getState().snapshot!.config).toMatchObject({routine:{foundation:{source:'local:missing'}}});player.dispose();});
});

describe('authentic bowl boundaries and cancellation',()=>{
    function signals(load=async()=>({duration:14.988} as AudioBuffer)){const f=native(),time=new FakeTiming(),p=defaultPreferences(),signals=new MeditationSignals(time,f.port,p,load),stage=snapshot(routine([med()])).stages[3],scope={sessionId:'one',stageId:'one/m',stage,start:0,deadline:600000};signals.begin('one');return{...f,time,p,signals,scope};}
    it('new custom defaults omit opening; closing plays one full-decay source and preserves natural tail',async()=>{const f=signals();f.signals.play(f.scope);expect(f.sources).toHaveLength(0);f.time.jump(600000);f.signals.play(f.scope,true);f.signals.play(f.scope,true);f.signals.stop('one',true);await flush();expect(f.sources).toHaveLength(1);expect(f.sources[0].stop).toHaveBeenCalledWith(14.988);expect(f.signals.diagnostics().activeNodes).toBe(1);f.sources[0].onended();expect(f.signals.diagnostics().activeNodes).toBe(0);});
    it('live Signals volume can mute a frozen block without changing its saved design',async()=>{const f=signals();f.p.volumes.signals=0;f.signals.setPreferences(f.p);f.time.jump(600000);f.signals.play(f.scope,true);await flush();expect(f.sources).toHaveLength(0);expect(f.scope.stage.soundRecipe?.closing).toBe('bowl');});
    it.each(['stop','new-start','hide','silent'] as const)('%s cancels pending recorded decay',async action=>{let resolve!:(b:AudioBuffer)=>void;const f=signals(()=>new Promise(r=>resolve=r));f.time.jump(600000);f.signals.play(f.scope,true);if(action==='new-start')f.signals.begin('two');else f.signals.stop('one');resolve({duration:15} as AudioBuffer);await flush();expect(f.sources).toHaveLength(0);});
    it('new Start immediately cancels an already ringing closing tail',async()=>{const f=signals();f.time.jump(600000);f.signals.play(f.scope,true);await flush();f.signals.begin('two');expect(f.sources[0].stop).toHaveBeenLastCalledWith();expect(f.signals.diagnostics().activeNodes).toBe(0);});
    it('frozen block signals survive unrelated global preference edits',async()=>{const f=signals();f.time.jump(600000);f.signals.play(f.scope,true);await flush();f.p.meditation.completionSignal=false;f.signals.setPreferences(f.p);expect(f.signals.diagnostics().activeNodes).toBe(1);f.signals.stop();});
    it('Silent/resuming/overdue scopes never emit bowl or chime',async()=>{const f=signals();f.time.jump(600000);f.signals.play({...f.scope,resuming:true},true);f.signals.play({...f.scope,stage:{...f.scope.stage,meditationPolicy:'silent'}},true);f.time.jump(251);f.signals.play(f.scope,true);await flush();expect(f.sources).toHaveLength(0);expect(f.oscillators).toHaveLength(0);});
    it('End Early records one parent result and no completion signal',()=>{const time=new FakeTiming(),completeStage=vi.fn(),audio={enter(){},cancelStage(){},cancelSession(){},completeStage},engine=new DeterministicSessionEngine(time,time,audio);engine.start(snapshot(routine([med()])));time.jump(14000);engine.reconcile();engine.stop('ended-early');expect(completeStage).not.toHaveBeenCalled();expect(engine.getState().result).toMatchObject({outcome:'cancelled',endReason:'ended-early',totalBlocks:1});});
});

describe('additive storage and full custom editor',()=>{
    it('selecting a real library track inside the editor cannot submit the routine form',async()=>{const save=vi.fn(),repository={list:async()=>[],save} as any;render(<Routines repository={repository} onStart={async()=>{}} onBack={()=>{}}/>);await waitFor(()=>expect(screen.getByRole('button',{name:'Create routine'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Create routine'}));fireEvent.change(screen.getByLabelText('Block 1 practice'),{target:{value:'meditation'}});fireEvent.change(screen.getByLabelText('Block 1 sound environment'),{target:{value:'custom'}});fireEvent.change(screen.getByLabelText('Block environment'),{target:{value:'selected'}});fireEvent.click(screen.getByText('Choose or import audio'));fireEvent.click(screen.getByRole('button',{name:'Select Home Again'}));expect(save).not.toHaveBeenCalled();expect(screen.getByLabelText('Routine name')).toBeInTheDocument();expect(screen.getByText(/Selected track: Home Again/)).toBeInTheDocument();});
    it('reopens schema 3 with exact custom recipes, duplicates them, and preserves unrelated records',async()=>{const db=new BuddyDatabase('acoustic-'+crypto.randomUUID()),repo=new RoutineRepository(db),r=routine([med('one'),med('two','custom',{...customMeditation(defaultPreferences()),source:'local:kept',mode:'baseline'})]);await db.open();await db.preferences.put(defaultPreferences());await db.media.put({id:'local:kept',displayName:'Kept',originalFilename:'synthetic.wav',mimeType:'audio/wav',byteSize:3,importedAt:'2026-10-09',blob:new Blob(['abc'])});await repo.save(r);db.close();await db.open();expect(db.verno).toBe(3);const saved=await repo.read(r.id);expect(saved.stages).toEqual(r.stages);expect(saved.foundation).toEqual(r.foundation);const copy=await repo.duplicate(r.id);expect(copy.stages.map(b=>b.kind==='meditation'?b.sound:undefined)).toEqual(r.stages.map(b=>b.kind==='meditation'?b.sound:undefined));expect(copy.stages[0].id).not.toBe(r.stages[0].id);expect((await db.media.get('local:kept'))?.byteSize).toBe(3);expect(await db.preferences.get('preferences')).toEqual(defaultPreferences());await db.delete();});
    it('corrupt sound stays stored and repair is only an explicit draft',async()=>{const db=new BuddyDatabase('acoustic-invalid-'+crypto.randomUUID()),repo=new RoutineRepository(db),r=routine();(r.stages[2] as any).sound.version=99;await db.routines.put(r);await expect(repo.read(r.id)).rejects.toThrow('repair');const repaired=repairDraft(r);expect(()=>validateRoutine(repaired)).not.toThrow();expect((await db.routines.get(r.id))!.stages[2]).toEqual(r.stages[2]);await db.delete();});
    it('builder pins the block, retains it on duplicate/reorder, and failed save leaves the draft',async()=>{const save=vi.fn().mockRejectedValue(new Error('storage full')),repository={list:async()=>[],save} as any;render(<Routines repository={repository} onStart={async()=>{}} onBack={()=>{}}/>);await waitFor(()=>expect(screen.getByRole('button',{name:'Create routine'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Create routine'}));fireEvent.change(screen.getByLabelText('Routine name'),{target:{value:'Deep sound'}});expect(screen.getByLabelText('Lead-in environment')).toHaveValue('generated');fireEvent.change(screen.getByLabelText('Block 1 practice'),{target:{value:'meditation'}});fireEvent.change(screen.getByLabelText('Block 1 sound environment'),{target:{value:'custom'}});fireEvent.change(screen.getByLabelText('Block binaural layer'),{target:{value:'layered'}});expect(screen.getByLabelText('Opening signal')).toHaveValue('off');expect(screen.getByLabelText('Closing signal')).toHaveValue('bowl');fireEvent.click(screen.getByRole('button',{name:'Duplicate block 1'}));fireEvent.click(screen.getByRole('button',{name:'Move block 2 up'}));fireEvent.click(screen.getByRole('button',{name:'Save routine'}));await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('storage full'));const r=save.mock.calls[0][0];expect(r.stages[0].sound).toEqual(r.stages[1].sound);expect(r.stages[0].sound.mode).toBe('layered');expect(screen.getByLabelText('Routine name')).toHaveValue('Deep sound');});
});
