import {describe,it,expect,vi} from 'vitest';
import {render,screen,fireEvent} from '@testing-library/react';
import {useState} from 'react';
import {signalProfile,toneEnvelope,freezeSound} from '../meditation/profile';
import {defaultPreferences,normalizePreferences,type BinauralMode} from '../settings/preferences';
import {createSnapshot} from '../session/config';
import {DeterministicSessionEngine} from '../session/engine';
import {BinauralController,createToneGraph,toneRecipe,modulationDepth,toneAmplitude} from '../audio/binaural';
import {generateMaskingBuffer} from '../audio/noise-spectrum';
import {FakeTiming} from './fake-time';
import {Meditation} from '../features/meditation/Meditation';
import type {PracticeRuntime} from '../session/runtime';
import {Navigation,pages} from '../components/Navigation';
const med=(seconds=600,policy:'defaults'|'silent'='defaults')=>({kind:'meditation' as const,presetId:'meditation' as const,durationSeconds:seconds,audioPolicy:policy});
function nativeMock(){
    const oscillators:any[]=[],gains:any[]=[],mergers:any[]=[];
    const node=()=>({connect:vi.fn(),disconnect:vi.fn()});
    const context={state:'running',currentTime:0,createOscillator:()=>{const o={...node(),frequency:{value:0},type:'sine',start:vi.fn(),stop:vi.fn(),onended:undefined as undefined|(()=>void)};oscillators.push(o);return o;},createGain:()=>{const g={...node(),gain:{value:1,setValueAtTime:vi.fn(),linearRampToValueAtTime:vi.fn(),cancelScheduledValues:vi.fn(),cancelAndHoldAtTime:vi.fn(),setTargetAtTime:vi.fn()}};gains.push(g);return g;},createChannelMerger:vi.fn(()=>{const m=node();mergers.push(m);return m;})};
    return{context,oscillators,gains,mergers,port:()=>({context,input:{}} as any)};
}
describe('immutable meditation recipe and exact profiles',()=>{
    it.each(Array.from({length:60},(_,i)=>i+1))('%i minutes remains valid and allocates exact positive time',minutes=>{const profile=signalProfile(minutes*60);expect(profile.entry+profile.steady+profile.return).toBe(minutes*60);expect(profile.steady).toBeGreaterThan(0);if(minutes>=10){expect(profile.entry).toBeGreaterThan(0);expect(profile.return).toBeGreaterThan(0);}expect(createSnapshot(med(minutes*60)).plannedDurationSeconds).toBe(minutes*60);});
    it.each([[10,1,8,1],[15,2,11,2],[20,2,15,3],[30,3,23,4],[45,4,35,6],[60,5,48,7]])('preset %i uses its specified allocation', (m,e,s,r)=>expect(signalProfile(m*60)).toEqual({entry:e*60,steady:s*60,return:r*60}));
    it('custom rule, boundaries and resume values have no frequency sweep or invalid endpoint',()=>{expect(signalProfile(660)).toEqual({entry:66,steady:515,return:79});const p=signalProfile(600);expect([-13,0,30,60,540,570,600].map(t=>Number(toneEnvelope(t,p,13).toFixed(8)))).toEqual([0,.2,.6,1,1,.5,0]);expect(toneEnvelope(60,signalProfile(60),13)).toBe(0);expect(()=>signalProfile(601)).toThrow();});
    it('freezes the recipe deeply without freezing live volume controls',()=>{const p=defaultPreferences();p.meditation.binaural.mode='layered';const snapshot=createSnapshot(med(),undefined,undefined,freezeSound(p));p.meditation.binaural.mode='off';p.meditation.noise='white';expect(snapshot.meditationSound).toEqual({version:1,mode:'layered',texture:'brown',music:false});expect(Object.isFrozen(snapshot.meditationSound)).toBe(true);});
    it.each(['off','brown','pink','white'] as const)('old %s preferences preserve sound, levels, tracks and shorter durations',noise=>{const p=defaultPreferences();p.meditation={...p.meditation,noise,noiseVolume:.23,durationMinutes:4,music:true};p.background.source='local:old';const old=structuredClone(p) as any;delete old.meditation.binaural;const migrated=normalizePreferences(old);expect(migrated).toEqual({...p,meditation:{...p.meditation,binaural:{mode:'off',level:.08}}});});
});
describe('native graph topology and cancellation',()=>{
    it.each(['baseline','layered','modulated'] as BinauralMode[])('%s routes exact carriers to isolated left/right inputs',mode=>{const f=nativeMock(),graph=createToneGraph(f.context as any,{} as any,mode,.08),pairs=toneRecipe(mode),carriers=f.oscillators.filter(o=>o.frequency.value!==40);expect(carriers.map(o=>o.frequency.value)).toEqual(pairs.flatMap(p=>[p.left,p.right]));expect(f.context.createChannelMerger).toHaveBeenCalledWith(2);const pairGains=f.gains.slice(mode==='modulated'?5:3);expect(pairGains.map(g=>g.connect.mock.calls[0]?.slice(1))).toEqual(pairs.flatMap(()=>[[0,0],[0,1]]));expect(pairs.reduce((n,p)=>n+p.gain*p.gain,0)).toBeCloseTo(1);if(mode==='modulated'){expect(f.oscillators.filter(o=>o.frequency.value===40)).toHaveLength(1);expect(modulationDepth).toBe(.15);}graph.start(0);graph.stop(20);graph.disconnect();graph.disconnect();for(const o of f.oscillators){expect(o.stop).toHaveBeenCalledWith(20);expect(o.disconnect).toHaveBeenCalledTimes(1);}});
    function controller(seconds=600,policy:'defaults'|'silent'='defaults') {const f=nativeMock(),clock=new FakeTiming(),p=defaultPreferences();p.meditation.binaural.mode='layered';const tones=new BinauralController(f.port,clock),engine=new DeterministicSessionEngine(clock,clock);tones.setPreferences(p);engine.subscribe(()=>tones.sync(engine.getState()));engine.start(createSnapshot(med(seconds,policy),undefined,undefined,freezeSound(p)));return{...f,clock,p,tones,engine};}
    it('creates once across Prepare/engine pulses, freezes mode, and changes only live level',()=>{const f=controller();expect(f.oscillators).toHaveLength(6);f.clock.advance(20000);expect(f.oscillators).toHaveLength(6);f.p.meditation.binaural={mode:'modulated',level:.12};f.tones.setPreferences(f.p);expect(f.oscillators).toHaveLength(6);expect(f.tones.getState().mode).toBe('layered');expect(f.gains[1].gain.setTargetAtTime).toHaveBeenCalledWith(toneAmplitude*.12,0,.05);f.engine.stop('ended-early');for(const o of f.oscillators)o.onended?.();expect(f.tones.diagnostics().activeOscillators).toBe(0);expect(f.engine.getState().result?.soundProfile?.mode).toBe('layered');});
    it.each([['short',60,'defaults'],['silent',600,'silent']] as const)('%s suppresses tones without changing the saved choice or deadline',(_,seconds,policy)=>{const f=controller(seconds,policy);expect(f.oscillators).toHaveLength(0);expect(f.p.meditation.binaural.mode).toBe('layered');f.clock.advance(13000+seconds*1000);expect(f.engine.getState().status).toBe('completed');});
    it('hide disconnects all nodes; resume uses current elapsed envelope and no old preview',()=>{const f=controller();f.tones.visibilityChanged(false);expect(f.tones.diagnostics().activeGraphs).toBe(0);f.clock.advance(583000);f.context.currentTime=583;f.tones.visibilityChanged(true);expect(f.oscillators).toHaveLength(12);expect(f.gains[9].gain.linearRampToValueAtTime.mock.calls[0][0]).toBeCloseTo(.499166,4);f.tones.dispose();expect(f.tones.diagnostics().activeGraphs).toBe(0);});
    it('later meditation observes the parent 3-second transition without new session timers',()=>{const f=nativeMock(),clock=new FakeTiming(),p=defaultPreferences();p.meditation.binaural.mode='baseline';const tones=new BinauralController(f.port,clock),engine=new DeterministicSessionEngine(clock,clock);tones.setPreferences(p);engine.subscribe(()=>tones.sync(engine.getState()));engine.start(createSnapshot({kind:'routine',routine:{id:'r',name:'later',createdAt:'2026-10-09',updatedAt:'2026-10-09',stages:[{id:'b',kind:'patterned',presetId:'box',durationSeconds:180},{id:'m',...med()}]}},undefined,undefined,freezeSound(p)));expect(f.oscillators).toHaveLength(0);clock.advance(193000);expect(f.oscillators).toHaveLength(2);expect(f.gains[0].gain.linearRampToValueAtTime).toHaveBeenCalledWith(.2,3);clock.advance(3000);expect(f.oscillators).toHaveLength(2);tones.dispose();});
    it('voice ducking does not repeatedly ramp when disabled or reopen after Stop',()=>{vi.useFakeTimers();try{const f=controller();f.tones.setDucking(true);f.tones.setDucking(false);f.engine.stop();vi.advanceTimersByTime(1000);expect(f.tones.diagnostics().held).toBe(false);f.p.guidance.ducking=false;f.tones.setPreferences(f.p);for(let n=0;n<20;n++)f.tones.setDucking(false);expect(f.gains[2].gain.setTargetAtTime).toHaveBeenCalledTimes(1);f.tones.dispose();}finally{vi.useRealTimers();}});
    it('audio interruption disposes frozen-clock graphs immediately and rejoins the current envelope',()=>{const f=controller();f.context.state='suspended';f.tones.sync(f.engine.getState());expect(f.tones.diagnostics().activeOscillators).toBe(0);for(const o of f.oscillators)expect(o.disconnect).toHaveBeenCalled();f.clock.advance(100000);f.context.state='running';f.tones.sync(f.engine.getState());expect(f.tones.diagnostics().activeOscillators).toBe(6);expect(f.engine.getState().remainingMs).toBe(513000);f.tones.dispose();});
});
describe('centered production masking and approachable controls',()=>{
    it('production masking copies one bounded DC-free periodic wave to both channels',async()=>{const channels:Float32Array[]=[];const context={sampleRate:48000,createBuffer:(_:number,n:number)=>({copyToChannel:(a:Float32Array,c:number)=>{channels[c]=a.slice();},length:n,numberOfChannels:2})};let seed=32;const random=vi.spyOn(Math,'random').mockImplementation(()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return(seed+.5)/4294967296;});const buffer=await generateMaskingBuffer(context as any,'brown',()=>false).finally(()=>random.mockRestore());expect(buffer.numberOfChannels).toBe(2);let delta=0;for(let i=0;i<channels[0].length;i++)delta=Math.max(delta,Math.abs(channels[0][i]-channels[1][i]));expect(delta).toBe(0);let peak=0,dc=0;const levels=[];for(let i=0;i<channels[0].length;i++){peak=Math.max(peak,Math.abs(channels[0][i]));dc+=channels[0][i];}for(let i=0;i+48000<channels[0].length;i+=48000){let e=0;for(let j=i;j<i+48000;j++)e+=channels[0][j]**2;levels.push(Math.sqrt(e/48000));}const mean=levels.reduce((n,x)=>n+x,0)/levels.length,cv=Math.sqrt(levels.reduce((n,x)=>n+(x-mean)**2,0)/levels.length)/mean;expect(peak).toBeLessThanOrEqual(.500001);expect(Math.abs(dc/channels[0].length)).toBeLessThan(1e-7);expect(cv).toBeLessThan(.03);});
    it('blocks short binaural Start explicitly, permits Off, and changes unified environment',()=>{const start=vi.fn(),runtime={stopNoisePreview:vi.fn()} as unknown as PracticeRuntime;function Setup(){const[p,set]=useState(()=>{const value=defaultPreferences();value.meditation.durationMinutes=4;value.meditation.binaural.mode='baseline';return value;});return <Meditation preferences={p} onChange={set} runtime={runtime} onStart={start}/>;}render(<Setup/>);fireEvent.click(screen.getByRole('button',{name:'Start meditation'}));expect(start).not.toHaveBeenCalled();expect(screen.getByRole('alert')).toHaveTextContent('10–60 minutes');fireEvent.change(screen.getByLabelText('Binaural layer'),{target:{value:'off'}});fireEvent.change(screen.getByLabelText('Environment'),{target:{value:'mix'}});expect(screen.getByLabelText('Masking texture')).toHaveValue('brown');fireEvent.change(screen.getByLabelText('Environment'),{target:{value:'selected'}});expect(screen.getByLabelText('Masking texture')).toHaveValue('off');fireEvent.click(screen.getByRole('button',{name:'Start meditation'}));expect(start).toHaveBeenCalledWith(med(240));});
    it('retains six named accessible navigation destinations and highlights Meditation',()=>{const navigate=vi.fn();render(<Navigation page="Meditation" onNavigate={navigate}/>);for(const name of pages)expect(screen.getByRole('button',{name})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Meditation'})).toHaveAttribute('aria-current','page');});
});
