import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import { createSnapshot, type ExerciseConfig, type PracticeConfig } from '../session/config';
import { DeterministicSessionEngine } from '../session/engine';
import { PracticeRuntime } from '../session/runtime';
import { FakeTiming } from './fake-time';
import { defaultPreferences, normalizePreferences, validPreferences } from '../settings/preferences';
import { meditationWindow, backgroundWanted } from '../meditation/policy';
import { Meditation } from '../features/meditation/Meditation';
import { MeditationSignals } from '../audio/meditation-signals';
import { BuddyDatabase } from '../storage/database';
import { RoutineRepository } from '../routines/repository';
import { stageCues } from '../audio/cues';
import { BackgroundController } from '../media/background';
const med=(minutes=1, audioPolicy:'defaults'|'silent'='defaults'):ExerciseConfig=>({kind:'meditation',presetId:'meditation',durationSeconds:minutes*60,audioPolicy});
const breathing:ExerciseConfig={kind:'patterned',presetId:'coherent',durationSeconds:180};
const routine=(blocks:ExerciseConfig[]):PracticeConfig=>({kind:'routine',routine:{id:'mixed',name:'Quiet finish',createdAt:'2026-10-09',updatedAt:'2026-10-09',stages:blocks.map((b,i)=>({...b,id:`block${i}`}))}});
function fixture(config:PracticeConfig=med()){const time=new FakeTiming(),audio={enter:vi.fn(),cancelStage:vi.fn(),cancelSession:vi.fn(),completeStage:vi.fn(),finishSession:vi.fn()},engine=new DeterministicSessionEngine(time,time,audio);engine.start(createSnapshot(config));return{time,audio,engine};}
describe('deterministic meditation',()=>{
    it.each([1,5,10,15,20,30,60])('compiles %i whole minutes excluding one Prepare',minutes=>{const snapshot=createSnapshot(med(minutes));expect(snapshot.stages.map(s=>[s.phase,s.durationMs])).toEqual([['prepare-inhale',4000],['prepare-exhale',6000],['prepare-settle',3000],['meditation',minutes*60000]]);expect(snapshot.plannedDurationSeconds).toBe(minutes*60);expect(Object.isFrozen(snapshot.config)).toBe(true);});
    it.each([0,59,61,90,3601,NaN,Infinity,-60,60.1])('rejects corrupt meditation seconds %s',durationSeconds=>{expect(()=>createSnapshot({...med(),durationSeconds} as PracticeConfig)).toThrow();expect(()=>createSnapshot(routine([{...med(),durationSeconds} as ExerciseConfig]))).toThrow();});
    it.each(['invalid',undefined])('rejects unsupported policy %s',audioPolicy=>expect(()=>createSnapshot({...med(),audioPolicy} as PracticeConfig)).toThrow());
    it.each([[med(),breathing],[breathing,med()],[med(),med(),breathing]])('uses one Prepare and 3-second transitions',(...blocks)=>{const s=createSnapshot(routine(blocks));expect(s.stages.filter(x=>x.phase.startsWith('prepare'))).toHaveLength(3);expect(s.stages.filter(x=>x.phase==='block-transition').map(x=>x.durationMs)).toEqual(blocks.slice(1).map(()=>3000));expect(s.stages.filter(x=>x.phase==='meditation')).toHaveLength(blocks.filter(x=>x.kind==='meditation').length);});
    it('finishes exactly, never exposes Release or speech/countdown, and emits one stage completion',()=>{const f=fixture();f.time.advance(13000);const scope=f.audio.enter.mock.calls.at(-1)![0];expect(stageCues(scope)).toEqual([]);expect(f.engine.getState().releaseAvailable).toBe(false);f.engine.releaseRetention();expect(f.engine.getState().stage?.phase).toBe('meditation');f.time.advance(59999);expect(f.engine.getState().status).toBe('running');f.time.advance(1);expect(f.engine.getState().result).toMatchObject({outcome:'completed',actualDurationSeconds:73,meditation:{plannedDurationSeconds:60,actualDurationSeconds:60}});expect(f.audio.completeStage).toHaveBeenCalledTimes(1);expect(f.audio.finishSession).toHaveBeenCalledTimes(1);});
    it('End Early excludes Prepare, cancels the whole routine and rejects old callbacks on Start Again',()=>{const f=fixture(routine([breathing,med(),breathing]));f.time.advance(196000+12345);const id=f.engine.getState().sessionId,stale=f.time.jobs.map(j=>j.callback),snapshot=f.engine.getState().snapshot!;f.engine.stop('ended-early');expect(f.engine.getState().result).toMatchObject({outcome:'cancelled',endReason:'ended-early',blocksCompleted:1,blocks:[{outcome:'completed',actualDurationSeconds:180},{outcome:'cancelled',actualDurationSeconds:12.345},{outcome:'not-started',actualDurationSeconds:0}]});expect(f.audio.completeStage).not.toHaveBeenCalled();f.engine.start(createSnapshot(snapshot.config));stale.forEach(cb=>cb());expect(f.engine.getState().stage?.phase).toBe('prepare-inhale');expect(f.engine.getState().sessionId).not.toBe(id);f.engine.stop();});
    it('records standalone partial time and no completion on cancellation',()=>{const f=fixture();f.time.advance(13000+4321);f.engine.stop('ended-early');expect(f.engine.getState().result?.meditation?.actualDurationSeconds).toBe(4.321);expect(f.audio.completeStage).not.toHaveBeenCalled();});
    it('hidden expiry reconciles once without replaying expired audio',()=>{const f=fixture();f.time.advance(13000);f.engine.setVisible(false);f.time.jump(100000);f.engine.setVisible(true);expect(f.engine.getState().status).toBe('completed');expect(f.audio.completeStage).toHaveBeenCalledTimes(1);/* Adapter filters expired timestamps; engine reports the absolute boundary. */expect(f.audio.completeStage.mock.calls[0][0].deadline).toBe(73000);expect(f.audio.enter).toHaveBeenCalledTimes(4);});
    it('hidden expiry suppresses signals when reconciled while still hidden',()=>{const f=fixture();f.engine.setVisible(false);f.time.advance(100000);expect(f.audio.completeStage).not.toHaveBeenCalled();expect(f.engine.getState().result?.meditation?.actualDurationSeconds).toBe(60);});
});
describe('shared meditation policy',()=>{
    it('routes the single existing media player after Master without a second volume authority or source node',async()=>{const element={paused:true,ended:false,volume:0,currentTime:0,duration:600,src:'',preload:'',loop:false,addEventListener(){},removeAttribute(){},load(){},pause(){this.paused=true;},play:vi.fn(async()=>{element.paused=false;})},node={connect:vi.fn(),disconnect:vi.fn()},input={},context={state:'running',createMediaElementSource:vi.fn(()=>node)};const bg=new BackgroundController({resolve:async()=>({url:'test',owned:false,name:'test'})},()=>element as any,()=>({context,input:{},mediaInput:input} as any));const p=defaultPreferences();p.background.source='ambience.floating';p.meditation.music=true;bg.setPreferences(p);await Promise.resolve();await Promise.resolve();const f=fixture();bg.sync(f.engine.getState());await Promise.resolve();await Promise.resolve();f.time.advance(13000);bg.sync(f.engine.getState());expect(context.createMediaElementSource).toHaveBeenCalledTimes(1);expect(context.createMediaElementSource).toHaveBeenCalledWith(element);expect(node.connect).toHaveBeenCalledWith(input);expect(element.play).toHaveBeenCalledTimes(1);bg.dispose();expect(node.disconnect).toHaveBeenCalledTimes(1);});
    it.each(['off','entire','retention','after'] as const)('explicit music overrides %s only within the lead-in/meditation window',mode=>{const f=fixture(routine([breathing,med(),breathing])),p=defaultPreferences();p.background.mode=mode;p.meditation.music=true;expect(backgroundWanted(f.engine.getState(),p)).toBe(mode==='entire');f.time.advance(193000);expect(meditationWindow(f.engine.getState())?.fadeDeadline).toBe(196000);expect(backgroundWanted(f.engine.getState(),p)).toBe(true);f.time.advance(3000);expect(backgroundWanted(f.engine.getState(),p)).toBe(true);p.meditation.music=false;expect(backgroundWanted(f.engine.getState(),p)).toBe(false);f.time.advance(60000);expect(backgroundWanted(f.engine.getState(),p)).toBe(mode==='entire');f.time.advance(183000);expect(backgroundWanted(f.engine.getState(),p)).toBe(mode==='after');});
    it.each(['off','entire','retention','after'] as const)('silent block suppresses %s through Prepare and meditation',mode=>{const f=fixture(med(1,'silent')),p=defaultPreferences();p.background.mode=mode;p.meditation.music=true;expect(meditationWindow(f.engine.getState())).toMatchObject({silent:true,start:0,fadeDeadline:13000});expect(backgroundWanted(f.engine.getState(),p)).toBe(false);f.time.advance(10000);expect(meditationWindow(f.engine.getState())?.fadeDeadline).toBe(13000);f.time.advance(3000);expect(backgroundWanted(f.engine.getState(),p)).toBe(false);f.engine.stop('ended-early');expect(backgroundWanted(f.engine.getState(),p)).toBe(false);});
});
describe('meditation defaults and saved blocks',()=>{
    it('normalizes legacy preferences without losing previous settings and validates caps',()=>{const p=defaultPreferences();p.volumes.voice=.22;const legacy={...p} as any;delete legacy.meditation;expect(normalizePreferences(legacy)).toMatchObject({volumes:{voice:.22},meditation:{durationMinutes:10,noise:'off',noiseVolume:.1}});for(const change of [{durationMinutes:0},{durationMinutes:1.5},{noise:'red'},{noiseVolume:.36},{noiseVolume:NaN},{openingSignal:'true'}])expect(validPreferences({...p,meditation:{...p.meditation,...change}})).toBe(false);});
    it('preserves schema 3, defaults and minimal meditation blocks across database reopen/duplicate',async()=>{const db=new BuddyDatabase(`med-${crypto.randomUUID()}`),repo=new RoutineRepository(db),p=defaultPreferences();p.meditation.noise='pink';p.meditation.noiseVolume=.08;await db.preferences.put(p);const row=(routine([med(),med(30,'silent')]) as Extract<PracticeConfig,{kind:'routine'}>).routine;await repo.save(row);const copy=await repo.duplicate(row.id);expect(copy.stages[0].id).not.toBe(row.stages[0].id);const name=db.name;db.close();const reopened=new BuddyDatabase(name);expect((await reopened.preferences.get('preferences'))?.meditation).toEqual(p.meditation);expect(reopened.verno).toBe(3);expect((await new RoutineRepository(reopened).read(row.id)).stages[1]).toMatchObject({kind:'meditation',durationSeconds:1800,audioPolicy:'silent'});await reopened.delete();});
    it('validates custom input before Start and keeps setup approachable',()=>{const p=defaultPreferences(),start=vi.fn(),runtime={stopNoisePreview:vi.fn()} as unknown as PracticeRuntime;render(<Meditation preferences={p} onChange={()=>{}} runtime={runtime} onStart={start} onChooseTrack={()=>{}}/>);fireEvent.change(screen.getByLabelText('Meditation duration'),{target:{value:'custom'}});for(const value of ['','0','61','1.5']){fireEvent.change(screen.getByLabelText('Custom minutes'),{target:{value}});fireEvent.click(screen.getByRole('button',{name:'Start meditation'}));expect(start).not.toHaveBeenCalled();}fireEvent.change(screen.getByLabelText('Custom minutes'),{target:{value:'1'}});fireEvent.click(screen.getByRole('button',{name:'Start meditation'}));expect(start).toHaveBeenCalledWith(med());expect(screen.queryByText('Pause')).toBeNull();});
});
describe('scoped synthetic signals',()=>{
    function signalFixture(){const clock=new FakeTiming(),oscillators:any[]=[],context={state:'running',currentTime:0,createOscillator:()=>{const o={frequency:{value:0},connect:vi.fn(),disconnect:vi.fn(),start:vi.fn(),stop:vi.fn()};oscillators.push(o);return o;},createGain:()=>({connect:vi.fn(),disconnect:vi.fn(),gain:{setValueAtTime:vi.fn(),linearRampToValueAtTime:vi.fn(),exponentialRampToValueAtTime:vi.fn(),cancelScheduledValues:vi.fn()}})};const p=defaultPreferences(),signals=new MeditationSignals(clock,()=>({context,input:{}} as any),p);const stage=createSnapshot(med()).stages[3],scope={sessionId:'one',stageId:'one/3',stage,start:13000,deadline:73000};return{clock,oscillators,p,signals,scope};}
    it('deduplicates opening and final completion, stops old ending tails on a new session',()=>{const f=signalFixture();f.clock.jump(13000);f.signals.play(f.scope);f.signals.play(f.scope);expect(f.oscillators).toHaveLength(2);f.signals.cancelStage(f.scope.stageId);expect(f.signals.diagnostics().activeNodes).toBe(0);f.clock.jump(60000);f.signals.play(f.scope,true);f.signals.play(f.scope,true);f.signals.stop('one',true);expect(f.signals.diagnostics()).toEqual({activeNodes:2,signalEvents:2});f.signals.begin('two');expect(f.signals.diagnostics()).toEqual({activeNodes:0,signalEvents:0});});
    it.each(['openingSignal','completionSignal'] as const)('independently honors %s and never replays expired events',key=>{const f=signalFixture();f.p.meditation[key]=false;f.signals.setPreferences(f.p);f.clock.jump(key==='openingSignal'?13000:73000);f.signals.play(f.scope,key==='completionSignal');expect(f.oscillators).toHaveLength(0);f.p.meditation[key]=true;f.clock.jump(1000);f.signals.play(f.scope,key==='completionSignal');expect(f.oscillators).toHaveLength(0);});
    it('silent policy and visibility resuming have no chime',()=>{const f=signalFixture();f.clock.jump(13000);f.signals.play({...f.scope,resuming:true});f.signals.play({...f.scope,stage:{...f.scope.stage,meditationPolicy:'silent'}});expect(f.oscillators).toHaveLength(0);});
});
