import { describe, it, expect, vi } from 'vitest';
import { generateNoise, fftSteps } from '../audio/noise-spectrum';
import { NoiseController } from '../audio/noise';
import { defaultPreferences, type NoiseColor } from '../settings/preferences';
import { createSnapshot } from '../session/config';
import { DeterministicSessionEngine } from '../session/engine';
import { FakeTiming } from './fake-time';
const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
function seeded(seed=8321){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return(seed+.5)/4294967296;};}
describe('empirical colored noise spectra',()=>{
    it.each([['white',0],['pink',-3.0103],['brown',-6.0206]] as const)('%s is finite, bounded, DC-free and has the expected power per Hz slope', (color,target)=>{
        const rate=48000,n=65536,samples=generateNoise(color,rate,n,seeded()),real=samples.slice(),imag=new Float32Array(n);for(const _ of fftSteps(real,imag)){/* complete */}
        const densities=[250,500,1000,2000,4000,8000].map(low=>{let sum=0,count=0;for(let k=Math.ceil(low*n/rate);k<Math.floor(low*2*n/rate);k++){sum+=real[k]**2+imag[k]**2;count++;}return 10*Math.log10(sum/count);});
        const slope=(densities.at(-1)!-densities[0])/5;expect(slope).toBeCloseTo(target,0);/* ±0.5 dB/octave across 250 Hz–16 kHz. */
        expect([...samples].every(Number.isFinite)).toBe(true);expect(Math.max(...samples.map(Math.abs))).toBeLessThanOrEqual(.500001);expect(Math.abs(samples.reduce((a,b)=>a+b,0)/n)).toBeLessThan(1e-7);
        let stepPower=0;for(let i=1;i<n;i++)stepPower+=(samples[i]-samples[i-1])**2;const seam=Math.abs(samples[0]-samples[n-1]);expect(seam).toBeLessThan(6*Math.sqrt(stepPower/(n-1)));/* Seam is an ordinary adjacent sample step, not a splice. */
    });
    it('independent channels have low correlation and reject invalid synthesis parameters',()=>{const a=generateNoise('pink',48000,32768,seeded(1)),b=generateNoise('pink',48000,32768,seeded(2));let cross=0,aa=0,bb=0;for(let i=0;i<a.length;i++){cross+=a[i]*b[i];aa+=a[i]**2;bb+=b[i]**2;}expect(Math.abs(cross/Math.sqrt(aa*bb))).toBeLessThan(.1);expect(()=>generateNoise('white',48000,1234)).toThrow();expect(()=>generateNoise('red' as NoiseColor,48000,1024)).toThrow();});
});
function fixture(build?:any){
    const sources:any[]=[],gains:any[]=[],context={state:'running',currentTime:0,sampleRate:48000,createBufferSource:()=>{const source={buffer:null,loop:false,connect:vi.fn(),disconnect:vi.fn(),start:vi.fn(),stop:vi.fn(),onended:undefined as undefined|(()=>void)};sources.push(source);return source;},createGain:()=>{const gain={connect:vi.fn(),disconnect:vi.fn(),gain:{value:1,setValueAtTime:vi.fn(),linearRampToValueAtTime:vi.fn(),cancelScheduledValues:vi.fn(),cancelAndHoldAtTime:vi.fn(),setTargetAtTime:vi.fn()}};gains.push(gain);return gain;}};
    const buffer={length:1<<20,numberOfChannels:2},create=build||vi.fn(async()=>buffer),noise=new NoiseController(()=>({context,input:{}} as any),create),p=defaultPreferences();p.meditation.noise='pink';noise.setPreferences(p);const time=new FakeTiming(),engine=new DeterministicSessionEngine(time,time);engine.subscribe(()=>noise.sync(engine.getState()));engine.start(createSnapshot({kind:'meditation',presetId:'meditation',durationSeconds:60,audioPolicy:'defaults'}));return{noise,p,time,engine,context,sources,gains,create};
}
describe('noise lifecycle and independent envelopes',()=>{
    it('later meditation uses precisely the existing 3-second transition ramp',async()=>{const f=fixture();await flush();f.engine.stop();f.sources[0].onended();f.gains.length=0;f.engine.start(createSnapshot({kind:'routine',routine:{id:'r',name:'Later',createdAt:'2026-10-09',updatedAt:'2026-10-09',stages:[{id:'b',kind:'patterned',presetId:'coherent',durationSeconds:180},{id:'m',kind:'meditation',presetId:'meditation',durationSeconds:60,audioPolicy:'defaults'}]}}));expect(f.noise.getState().playing).toBe(false);f.time.advance(193000);await flush();expect(f.engine.getState().stage?.phase).toBe('block-transition');expect(f.gains[0].gain.linearRampToValueAtTime).toHaveBeenCalledWith(1,3);f.time.advance(3000);await flush();expect(f.gains[0].gain.linearRampToValueAtTime).toHaveBeenCalledTimes(1);f.noise.dispose();});
    it('ramps across Prepare once, stays stable on engine pulses, and levels avoid a second Master multiplication',async()=>{const f=fixture();await flush();expect(f.sources).toHaveLength(1);expect(f.gains[0].gain.linearRampToValueAtTime).toHaveBeenCalledWith(1,13);expect(f.gains[2].gain.setValueAtTime).toHaveBeenCalledWith(.1,0);f.time.advance(13000+3000);await flush();expect(f.sources).toHaveLength(1);expect(f.gains[0].gain.linearRampToValueAtTime).toHaveBeenCalledTimes(1);f.p.volumes.master=.2;f.p.meditation.noiseVolume=.08;f.noise.setPreferences(f.p);expect(f.gains[2].gain.setTargetAtTime).toHaveBeenCalledWith(.08,0,.05);f.engine.stop('ended-early');expect(f.noise.diagnostics().playing).toBe(false);expect(f.sources[0].stop).toHaveBeenCalledWith(.05);f.sources[0].onended();expect(f.noise.diagnostics().activeNodes).toBe(0);});
    it('voice ducking bridges short speech gaps without pumping or getting stuck after voice is disabled',async()=>{vi.useFakeTimers();try{const f=fixture();await flush();f.noise.setDucking(true);f.context.currentTime=.25;expect(f.noise.diagnostics().duckFactor).toBe(.4);f.noise.setDucking(false);vi.advanceTimersByTime(200);f.noise.setDucking(true);expect(f.gains[1].gain.linearRampToValueAtTime).toHaveBeenCalledTimes(1);f.noise.setDucking(false);vi.advanceTimersByTime(300);f.context.currentTime=.5;expect(f.noise.diagnostics().duckFactor).toBe(1);f.p.guidance.ducking=false;f.noise.setPreferences(f.p);expect(f.noise.diagnostics().held).toBe(false);f.noise.dispose();}finally{vi.useRealTimers();}});
    it('live type change crossfades, caches at most two colors, and removes every retired graph',async()=>{const f=fixture();await flush();for(const color of ['white','brown','pink'] as const){f.p.meditation.noise=color;f.noise.setPreferences(f.p);await flush();expect(f.gains.at(-3).gain.linearRampToValueAtTime).toHaveBeenCalledWith(1,.3);for(const s of f.sources.slice(0,-1))s.onended();expect(f.noise.diagnostics().activeNodes).toBe(1);expect(f.noise.diagnostics().cachedBuffers).toBeLessThanOrEqual(2);}expect(f.noise.diagnostics().bufferBytes).toBe(16*1024*1024);f.noise.visibilityChanged(false);expect(f.noise.diagnostics().activeNodes).toBe(0);expect(f.noise.diagnostics().playing).toBe(false);});
    it('Stop/visibility invalidates pending synthesis; a late completion cannot start old audio',async()=>{let resolve!:(v:any)=>void;const f=fixture(()=>new Promise(r=>{resolve=r;}));f.noise.visibilityChanged(false);resolve({length:1024,numberOfChannels:2});await flush();expect(f.sources).toHaveLength(0);expect(f.noise.diagnostics().pending).toBeUndefined();expect(f.noise.diagnostics().cachedBuffers).toBe(0);});
    it('synthesis failure never changes the authoritative deadline',async()=>{const f=fixture(async()=>{throw new Error('failed');});await flush();expect(f.noise.getState().error).toContain('Meditation continues');f.time.advance(73000);expect(f.engine.getState().status).toBe('completed');});
    it('preview needs its own context, ends when a session starts, and silent policy keeps noise suppressed',async()=>{const f=fixture();await flush();f.engine.stop();f.noise.preview();await flush();expect(f.noise.getState().preview).toBe(true);f.engine.start(createSnapshot({kind:'meditation',presetId:'meditation',durationSeconds:60,audioPolicy:'silent'}));await flush();expect(f.noise.getState().preview).toBe(false);expect(f.noise.getState().playing).toBe(false);f.noise.dispose();});
});
